### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/TGS#1]
Please change login page background to this video - http://demos.artbees.net/jupiter/sinope/

I don't quite get why you changed the design of login form and changed login button to red, if we have already beautiful transparent design of login form in design I sent
![login](https://cloud.githubusercontent.com/assets/592627/9933440/9199232e-5d53-11e5-92f5-8fb8baaf74c3.JPG)

Please don't use red colors as I mentioned before cause usually people user red to delete something, not to login

**Comment by Aram4ik** [comment]
Also would be nice to show that page is loading after click, cause even I clicked twice to login.

**Comment by agilecubeteam** [comment]
fixed.
