### ISSUE TITLE
Sync service

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/TGS#10]
what is it?
and it doesn't work

**Comment by agilecubeteam** [comment]
it is web based service which sends system generated emails.
We provided options for admin to start and stop it.

**Comment by Aram4ik** [comment]
Hm.. It should be full automatic. I mean even if my computer is closed it should work..

**Comment by agilecube** [comment]
This is just an extra facility for admin to start/stop in case of some emergency. Of-course, service will be fully automatic and all time running.
