### ISSUE TITLE
Questionnaire radio buttons to checkboxes

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/TGS#3]
I can't select 2 correct answers in questionnaire

**Comment by agilecubeteam** [comment]
It is as per requirement, and given in prototype. Let us know if change is needed. 

https://drive.google.com/open?id=0BwY3d84SSYlLakpQSTdiV0FHd1E

Personal Note: It is much easier for user to select one answer, and see if it is correct or not. As objective of the system is to make user learn about the system and not to take real test :)

**Comment by Aram4ik** [comment]
Yes, please. Checkboxes are needed.

We need to make a real test to be sure user know how to use system which will bring him money. Otherwise he will be disappointed and will spread wrong information.

**Comment by agilecube** [comment]
We can do this in next phase. :). 
Please close this as of now.
