### ISSUE TITLE
Blueprint

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/TGS#7]
Please check out the blueprint - https://realtimeboard.com/app/board/94641865/

Screenshot is here
![3231](https://cloud.githubusercontent.com/assets/592627/9934250/c03f67a6-5d58-11e5-9bf5-8ed8ab05f329.png)

**Comment by agilecubeteam** [comment]
@Aram4ik 
We really don't understand why we are discussion flow again? we have already discussed flow and finalize it.
Development was based on what we discussed.

**Comment by agilecubeteam** [comment]
Please close this issue, as it has no meaning. We have sign-off requirement available on Drive:

https://drive.google.com/open?id=0BwY3d84SSYlLaUdVOE1laEExYzA

And All Approved Prototype are also available on drive:

https://drive.google.com/open?id=0BwY3d84SSYlLVTBuc0wwcE9GV0k
